export { createDaftarProto } from './proto'
export type { DaftarProtoDeps } from './proto'
export { parseDaftarSpec } from './spec'
export type { DaftarSpec, EstudianteSpec } from './spec'
export { crearInstrumentos, idSeguro } from './instrumentos'
export type { Instrumentos, InstrumentosDeps, GuiaMeta, GuiaCargada } from './instrumentos'
export { renderShell, INDEX_HTML, APP_JS, STYLE_CSS } from './assets'
export type { DaftarBootstrap } from './assets'
export { renderReport } from './report'
export { renderPrint } from './print'
export { atenderDaftar } from './let'
export type { DaftarDeps, DaftarStore } from './let'
export type { Guia, Progreso, EstudianteInfo } from './tipos'
